services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args: 
        # Update the VARIANT arg to pick a Java version: 11, 17
        # Append -bullseye or -buster to pin to an OS version.
        # Use the -bullseye variants on local arm64/Apple Silicon.
        VARIANT: "17-bullseye"
        # Options
        INSTALL_MAVEN: "true"
        INSTALL_GRADLE: "false"
        NODE_VERSION: "lts/*"
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

    # Runs app on the same network as the database container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:db

    volumes:
      # Update this to wherever you want VS Code to mount the folder of your project
      - ..:/workspace:cached

      # Uncomment the next line to use Docker from inside the container. See https://aka.ms/vscode-remote/samples/docker-from-docker-compose for details.
      # - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/data/db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Password!23
      - POSTGRES_DB=book_library
volumes:
  postgres-data: